class Vibelens < Formula
  include Language::Python::Virtualenv

  desc "Agent trajectory analysis and visualization platform"
  homepage "https://vibelens.chats-lab.org/"
  url "https://files.pythonhosted.org/packages/source/v/vibelens/vibelens-0.9.31.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256"
  license "MIT"

  depends_on "python@3.12"

  # Resource blocks are auto-generated by homebrew-pypi-poet.
  # To regenerate:
  #   pip install vibelens homebrew-pypi-poet
  #   poet -f vibelens
  #
  # Then paste ALL resource blocks here, replacing this comment.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vibelens version")
  end
end
